version: '3'
services:
  phalcon:
    container_name: phalcon
    image: phalcon:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/.ssh:/root/.ssh
      - ./httpd/logs:/var/log/apache2
      - ./projects:/var/www/html
      - ./httpd/vhosts:/etc/apache2/sites-enabled
